import type { ReportTemplate, ReportTemplateRow } from "@/features/reports/templates/types";

const sourceSheetName = "new SUMMARY 21-MAY-26";

const readonlyRowKeys = [
  "stock_formula_total_row_62",
  "stock_daily_snapshot_row_64",
  "hold_section_header_row_66",
  "hold_total_row_87",
  "line_section_header_row_93",
  "line_total_row_100",
  "closing_balance_row_102",
  "worksheet_footer_row_103",
];

function sourceRow(row: Omit<ReportTemplateRow, "sourceSheetName">): ReportTemplateRow {
  return {
    sourceSheetName,
    ...row,
  };
}

export const wfTestShadeTemplate: ReportTemplate = {
  id: "wf-test-shade",
  name: "WF Test & Shade",
  description: "Manual AG Grid model of the production WF Test & Shade worksheet.",
  operationalLabel: "WF Test & Shade worksheet",
  match: (report) => {
    const haystack = [
      report.report_type_name,
      report.title,
      typeof report.metadata.template === "string" ? report.metadata.template : null,
      typeof report.metadata.excel_template_key === "string" ? report.metadata.excel_template_key : null,
    ]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();

    return (
      haystack.includes("wf") ||
      haystack.includes("wet finishing") ||
      haystack.includes("shade")
    );
  },
  baseColumns: [
    { field: "row_label", headerName: "Operational block", minWidth: 250, pinned: "left" },
    { field: "row_group", headerName: "Worksheet section", minWidth: 180 },
    { field: "row_key", headerName: "Source row key", minWidth: 190 },
  ],
  sections: [
    {
      id: "shade_test_stock",
      label: "T/Stock - Shade & Test",
      rowGroup: "shade_test_stock",
      description: "Main C&A stock blocks from rows 5-61 of the worksheet.",
      allowDynamicRows: true,
    },
    {
      id: "stock_totals",
      label: "Daily Stock Totals",
      rowGroup: "stock_totals",
      description: "Formula and daily snapshot bands from rows 62-64.",
      allowDynamicRows: false,
      readonly: true,
    },
    {
      id: "test_hold",
      label: "Test Purpose Hold",
      rowGroup: "test_hold",
      description: "C&A hold-only and buyer-wise test-purpose hold rows.",
      allowDynamicRows: true,
    },
    {
      id: "line_shade_test",
      label: "Line Shade/Test Balance",
      rowGroup: "line_shade_test",
      description: "Secondary line block from rows 93-100.",
      allowDynamicRows: true,
    },
    {
      id: "closing_summary",
      label: "Closing Summary",
      rowGroup: "closing_summary",
      description: "Bottom availability and worksheet footer rows.",
      allowDynamicRows: false,
      readonly: true,
    },
  ],
  metricColumns: [
    {
      key: "total_stock_shade_test_kg",
      label: "T/Stock shade & test",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "shade_test_stock",
      defaultValue: "0",
    },
    {
      key: "buyer",
      label: "Buyer",
      valueType: "text",
      sectionId: "shade_test_stock",
      defaultValue: "",
    },
    {
      key: "wait_for_test_kg",
      label: "Wait for test",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "shade_test_stock",
      defaultValue: "0",
    },
    {
      key: "wait_for_test_buyer",
      label: "Test buyer",
      valueType: "text",
      sectionId: "shade_test_stock",
      defaultValue: "",
    },
    {
      key: "wait_for_shade_kg",
      label: "Wait for shade",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "shade_test_stock",
      defaultValue: "0",
    },
    {
      key: "wait_for_shade_buyer",
      label: "Shade buyer",
      valueType: "text",
      sectionId: "shade_test_stock",
      defaultValue: "",
    },
    {
      key: "wait_for_rfd_kg",
      label: "Wait for RFD",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "shade_test_stock",
      defaultValue: "0",
    },
    {
      key: "hold_only_ca_kg",
      label: "Hold only C&A",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "test_hold",
      defaultValue: "0",
    },
    {
      key: "ca_grand_total_kg",
      label: "C&A grand total",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "test_hold",
      defaultValue: "0",
    },
    {
      key: "test_hold_grand_total_kg",
      label: "Hold grand total",
      valueType: "number",
      unitOfMeasure: "kg",
      sectionId: "test_hold",
      defaultValue: "0",
    },
    {
      key: "remarks",
      label: "Remarks",
      valueType: "text",
      sectionId: "closing_summary",
      defaultValue: "",
    },
  ],
  rows: [
    sourceRow({
      key: "stock_ca_normal_row_5_16",
      label: "HTL-02 / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 5,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 5-16" },
    }),
    sourceRow({
      key: "stock_ca_normal_row_17_29",
      label: "CCL-A / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 17,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 17-29" },
    }),
    sourceRow({
      key: "stock_ca_normal_row_30_36",
      label: "CCL-B / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 30,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 30-36" },
    }),
    sourceRow({
      key: "stock_ca_normal_row_37_44",
      label: "MTL / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 37,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 37-44" },
    }),
    sourceRow({
      key: "stock_ca_normal_row_45_54",
      label: "HTL / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 45,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 45-54" },
    }),
    sourceRow({
      key: "stock_ca_normal_row_55_61",
      label: "CCL-07 / C&A normal stock",
      rowGroup: "shade_test_stock",
      sourceRowNumber: 55,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (NORMAL)", remarks: "Worksheet rows 55-61" },
    }),
    sourceRow({
      key: "stock_formula_total_row_62",
      label: "Stock formula total",
      rowGroup: "stock_totals",
      sourceRowNumber: 62,
      role: "calculated",
      readonly: true,
      visualLevel: 0,
      metricDefaults: { remarks: "Read-only worksheet formula band" },
    }),
    sourceRow({
      key: "stock_daily_snapshot_row_64",
      label: "Daily stock snapshot",
      rowGroup: "stock_totals",
      sourceRowNumber: 64,
      role: "summary",
      readonly: true,
      visualLevel: 0,
      metricDefaults: {
        total_stock_shade_test_kg: "72109",
        wait_for_test_kg: "69173",
        wait_for_shade_kg: "1882",
        wait_for_rfd_kg: "1054",
        remarks: "Read-only daily worksheet totals",
      },
    }),
    sourceRow({
      key: "hold_section_header_row_66",
      label: "Test purpose hold header",
      rowGroup: "test_hold",
      sourceRowNumber: 66,
      role: "summary",
      readonly: true,
      visualLevel: 0,
      metricDefaults: {
        remarks: "Merged header row in worksheet",
      },
    }),
    sourceRow({
      key: "hold_hm_row_67",
      label: "CCL / H&M test-purpose hold",
      rowGroup: "test_hold",
      sourceRowNumber: 67,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "H&M" },
    }),
    sourceRow({
      key: "hold_ca_row_68",
      label: "HTL-2 / PUMA test-purpose hold",
      rowGroup: "test_hold",
      sourceRowNumber: 68,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "PUMA" },
    }),
    sourceRow({
      key: "hold_ca_row_69",
      label: "MHTL / VF Asia test-purpose hold",
      rowGroup: "test_hold",
      sourceRowNumber: 69,
      role: "editable",
      visualLevel: 2,
      metricDefaults: { buyer: "VF ASIA" },
    }),
    sourceRow({
      key: "hold_ca_row_70",
      label: "CCL-07 / Intimate test-purpose hold",
      rowGroup: "test_hold",
      sourceRowNumber: 70,
      role: "editable",
      visualLevel: 2,
      metricDefaults: { buyer: "INTIMATE" },
    }),
    sourceRow({
      key: "hold_buyer_rows_71_86",
      label: "Buyer-wise hold detail rows",
      rowGroup: "test_hold",
      sourceRowNumber: 71,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { remarks: "Worksheet rows 71-86" },
    }),
    sourceRow({
      key: "hold_total_row_87",
      label: "Test purpose hold total",
      rowGroup: "test_hold",
      sourceRowNumber: 87,
      role: "calculated",
      readonly: true,
      visualLevel: 0,
      metricDefaults: {
        ca_grand_total_kg: "17362",
        remarks: "Read-only hold section total",
      },
    }),
    sourceRow({
      key: "line_section_header_row_93",
      label: "Line shade/test header",
      rowGroup: "line_shade_test",
      sourceRowNumber: 93,
      role: "summary",
      readonly: true,
      visualLevel: 0,
      metricDefaults: { remarks: "Header row" },
    }),
    sourceRow({
      key: "line_ca_lin_row_94",
      label: "C&A line shade/test detail 1",
      rowGroup: "line_shade_test",
      sourceRowNumber: 94,
      role: "editable",
      visualLevel: 1,
      metricDefaults: {
        buyer: "C&A (Lin)",
        wait_for_test_buyer: "H&M",
      },
    }),
    sourceRow({
      key: "line_ca_lin_rows_95_99",
      label: "C&A line shade/test details",
      rowGroup: "line_shade_test",
      sourceRowNumber: 95,
      role: "editable",
      visualLevel: 1,
      metricDefaults: { buyer: "C&A (Lin)", remarks: "Worksheet rows 95-99" },
    }),
    sourceRow({
      key: "line_total_row_100",
      label: "Line shade/test total",
      rowGroup: "line_shade_test",
      sourceRowNumber: 100,
      role: "calculated",
      readonly: true,
      visualLevel: 0,
      metricDefaults: { remarks: "Read-only line section total" },
    }),
    sourceRow({
      key: "closing_balance_row_102",
      label: "Closing availability balance",
      rowGroup: "closing_summary",
      sourceRowNumber: 102,
      role: "calculated",
      readonly: true,
      visualLevel: 0,
      metricDefaults: {
        total_stock_shade_test_kg: "12887",
        wait_for_test_kg: "364",
        wait_for_shade_kg: "12523",
        remarks: "Read-only final worksheet balance",
      },
    }),
    sourceRow({
      key: "worksheet_footer_row_103",
      label: "Worksheet footer band",
      rowGroup: "closing_summary",
      sourceRowNumber: 103,
      role: "summary",
      readonly: true,
      visualLevel: 0,
      metricDefaults: { remarks: "Final merged worksheet band" },
    }),
  ],
  pinnedRows: [
    {
      id: "wf_test_source_summary",
      label: "Workbook summary",
      position: "top",
      values: {
        row_group: "summary",
        row_key: "wf_test_source_summary",
        total_stock_shade_test_kg: "72109",
        wait_for_test_kg: "69173",
        wait_for_shade_kg: "1882",
        wait_for_rfd_kg: "1054",
        ca_grand_total_kg: "17362",
        remarks: `${sourceSheetName} / A1:M103`,
      },
    },
  ],
  readonlyRowKeys,
  summary: {
    showMetricCount: true,
    showRowCount: true,
    pinnedSummaryRows: true,
  },
};
