"""add_sub_unit_department

Revision ID: 88ba57cdd6b2
Revises: 20260601120000
Create Date: 2026-06-04 16:34:42.489792
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '88ba57cdd6b2'
down_revision = '20260601120000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_facts', sa.Column('sub_unit', sa.String(length=255), nullable=True))
    op.add_column('operational_facts', sa.Column('department', sa.String(length=255), nullable=True))
    op.create_index('operational_facts_department_date_idx', 'operational_facts', ['department', 'report_date'], unique=False)
    op.create_index('operational_facts_sub_unit_date_idx', 'operational_facts', ['sub_unit', 'report_date'], unique=False)
    op.create_index('operational_facts_unit_sub_unit_idx', 'operational_facts', ['unit', 'sub_unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('operational_facts_unit_sub_unit_idx', table_name='operational_facts')
    op.drop_index('operational_facts_sub_unit_date_idx', table_name='operational_facts')
    op.drop_index('operational_facts_department_date_idx', table_name='operational_facts')
    op.drop_column('operational_facts', 'department')
    op.drop_column('operational_facts', 'sub_unit')
    # ### end Alembic commands ###
